{
 "title": "AEM Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "host", "query": "localhost" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU usage as reported by JVM.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.granite.*.CPU.LOAD.PERCENTAGE.v, 2)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.granite.FREE.PHYSICAL.MEMORY.SIZE.v, 2, 3)"
    },
    {
     "target": "aliasByNode($host.granite.HEAP.USED.v, 2, 3)"
    },
    {
     "target": "aliasByNode($host.granite.HEAP.MAX.v, 2, 3)"
    },
    {
     "target": "aliasByNode($host.granite.NON.HEAP.USED.v, 2, 3, 4)"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.granite.DISK.USABLE.SPACE.v, 2, 3, 4)"
    },
    {
     "target": "aliasByNode($host.oak.SEGMENT.REPO.SIZE.v, 2, 3, 4)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU usage as reported by operating system.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.granite.system.cpu.user.v, 4)"
    },
    {
     "target": "aliasByNode($host.granite.system.cpu.system.v, 4)"
    },
    {
     "target": "aliasByNode($host.granite.system.cpu.iowait.v, 4)"
    },
    {
     "target": "aliasByNode($host.granite.system.cpu.nice.v, 4)"
    },
    {
     "target": "aliasByNode($host.granite.system.cpu.idle.v, 4)"
    }
   ]
  },
  {
   "title": "Process memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.granite.process.memory.*.v, 4)"
    }
   ]
  },
  {
   "title": "System memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.granite.system.memory.*.v, 4)"
    }
   ]
  },
  {
   "title": "I/O read (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.granite.process.io.read.v, 4)"
    },
    {
     "target": "aliasByNode($host.granite.process.io.disk.read.v, 4, 5)"
    }
   ]
  },
  {
   "title": "I/O write (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.granite.process.io.write.v, 4)"
    },
    {
     "target": "aliasByNode($host.granite.process.io.disk.write.v, 4, 5)"
    },
    {
     "target": "aliasByNode($host.granite.process.io.cancelled.write.v, 4, 5)"
    }
   ]
  },
  {
   "title": "Network (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.granite.system.network.*.v, 4)"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.granite.OPEN.FILE.DESCRIPTOR.COUNT.v, 2, 3, 4)"
    }
   ]
  },
  {
   "title": "Session",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias($host.oak.SESSION.COUNT.v, 'Open sessions')"
    },
    {
     "target": "alias($host.oak.SESSION.LOGIN.COUNTER.v, 'Logins/s')"
    },
    {
     "target": "alias($host.oak.SESSION.WRITE.COUNTER.v, 'Writes/s')"
    }
   ]
  },
  {
   "title": "Observation",
   "type": "graph",
   "description": "Delivered events per second.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.oak.OBSERVATION.EVENT.COUNTER.v, 3, 4)"
    }
   ]
  },
  {
   "title": "Segment I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.oak.oak.segment.*.v, 4)"
    }
   ]
  },
  {
   "title": "Segment Commits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.oak.COMMIT.QUEUE.SIZE.v, 3, 4)"
    },
    {
     "target": "aliasByNode($host.oak.COMMITS.COUNT.v, 2)"
    },
    {
     "target": "aliasByNode($host.oak.JOURNAL.WRITES.v, 2, 3)"
    }
   ]
  },
  {
   "title": "Segment Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias($host.oak.CacheStats.*.loadTime.v, 'loadTime')"
    }
   ]
  },
  {
   "title": "NRT updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.oak.oak.index.*.NRT.UPDATES.v, 4)"
    }
   ]
  },
  {
   "title": "Hybrid index",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.oak.HYBRID.ADDED.v, 3)"
    },
    {
     "target": "aliasByNode($host.oak.HYBRID.DROPPED.v, 3)"
    },
    {
     "target": "aliasByNode($host.oak.HYBRID.EXTERNAL.ADDED.select metric, 3, 4)"
    }
   ]
  },
  {
   "title": "Async indexer (nodes/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.oak.*.INDEXER.NODE.COUNT.v, 2)"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias($host.sling.granite.request.metrics.timer.v, 'requests/s')"
    }
   ]
  },
  {
   "title": "Asset updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.sling.cq.dam.asset.updates.ongoing.v, 6)"
    },
    {
     "target": "aliasByNode($host.sling.cq.dam.asset.updates.v, 5)"
    }
   ]
  },
  {
   "title": "Blob",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.oak.BLOB.*.COUNT.v, 3)"
    }
   ]
  },
  {
   "title": "DocumentNodeStore",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.oak.DOCUMENT.NS.BGR.NUM.CHANGES.RATE.v, 4, 6)"
    },
    {
     "target": "aliasByNode($host.oak.DOCUMENT.NS.BGW.NUM.WRITE.RATE.v, 4, 6)"
    },
    {
     "target": "aliasByNode($host.oak.DOCUMENT.NS.MERGE.SUCCESS.COUNT.v, 4, 5)"
    },
    {
     "target": "aliasByNode($host.oak.DOCUMENT.NS.BRANCH.COMMIT.COUNT.v, 4, 5)"
    },
    {
     "target": "aliasByNode($host.oak.DOCUMENT.NS.MERGE.BRANCH.COMMIT.COUNT.v, 4, 5, 6)"
    }
   ]
  },
  {
   "title": "DocumentStore",
   "type": "graph",
   "description": "The rate of calls per second for each kind of operation.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.oak.DOCUMENT.NODES.CREATE.TIMER.v, 4)"
    },
    {
     "target": "aliasByNode($host.oak.DOCUMENT.NODES.CREATE.UPSERT.TIMER.v, 5)"
    },
    {
     "target": "aliasByNode($host.oak.DOCUMENT.NODES.FIND.PRIMARY.v, 4, 5)"
    },
    {
     "target": "aliasByNode($host.oak.DOCUMENT.NODES.QUERY.PRIMARY.v, 4, 5)"
    },
    {
     "target": "aliasByNode($host.oak.DOCUMENT.NODES.QUERY.SLAVE.v, 4, 5)"
    },
    {
     "target": "aliasByNode($host.oak.DOCUMENT.NODES.REMOVE.TIMER.v, 4)"
    },
    {
     "target": "aliasByNode($host.oak.DOCUMENT.NODES.UPDATE.v, 4)"
    }
   ]
  },
  {
   "title": "DocumentNodeStore RGC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.oak.RevisionGC.*.*.v, 3, 4)"
    },
    {
     "target": "aliasByNode($host.oak.RevisionGC.*.*.*.v, 3, 4, 5)"
    },
    {
     "target": "aliasByNode($host.oak.RevisionGC.*.*.*.*.v, 3, 4, 5, 6)"
    }
   ]
  },
  {
   "title": "MongoDB nodes collection",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.oak.MongoDB.nodes.size.v, 4)"
    },
    {
     "target": "aliasByNode($host.oak.MongoDB.nodes.storageSize.v, 4)"
    }
   ]
  },
  {
   "title": "MongoDB blobs collection",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.oak.MongoDB.blobs.size.v, 4)"
    },
    {
     "target": "aliasByNode($host.oak.MongoDB.blobs.storageSize.v, 4)"
    }
   ]
  },
  {
   "title": "MongoDB journal collection",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.oak.MongoDB.journal.size.v, 4)"
    }
   ]
  },
  {
   "title": "CacheStats - hit rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(asPercent(#B, #A), 3)",
     "targetFull": "aliasByNode(asPercent($host.oak.CacheStats.Document-NodeState.hit.v, $host.oak.CacheStats.Document-NodeState.request.v), 3)"
    },
    {
     "target": "aliasByNode(asPercent(#E, #D), 3)",
     "targetFull": "aliasByNode(asPercent($host.oak.CacheStats.Document-Documents.hit.v, $host.oak.CacheStats.Document-Documents.request.v), 3)"
    },
    {
     "target": "aliasByNode(asPercent(#H, #G), 3)",
     "targetFull": "aliasByNode(asPercent($host.oak.CacheStats.Document-LocalDiff.hit.v, $host.oak.CacheStats.Document-LocalDiff.request.v), 3)"
    },
    {
     "target": "aliasByNode(asPercent(#K, #J), 3)",
     "targetFull": "aliasByNode(asPercent($host.oak.CacheStats.Document-MemoryDiff.hit.v, $host.oak.CacheStats.Document-MemoryDiff.request.v), 3)"
    },
    {
     "target": "aliasByNode(asPercent(#N, #M), 3)",
     "targetFull": "aliasByNode(asPercent($host.oak.CacheStats.Document-NodeChildren.hit.v, $host.oak.CacheStats.Document-NodeChildren.request.v), 3)"
    },
    {
     "target": "aliasByNode(asPercent(#Q, #P), 3)",
     "targetFull": "aliasByNode(asPercent($host.oak.CacheStats.Document-PrevDocuments.hit.v, $host.oak.CacheStats.Document-PrevDocuments.request.v), 3)"
    }
   ]
  },
  {
   "title": "PersistentCache - hit rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(asPercent(#B, #A), 4)",
     "targetFull": "aliasByNode(asPercent($host.oak.PersistentCache.NodeCache.children.HITS.v, $host.oak.PersistentCache.NodeCache.children.REQUESTS.v), 4)"
    },
    {
     "target": "aliasByNode(asPercent(#E, #D), 4)",
     "targetFull": "aliasByNode(asPercent($host.oak.PersistentCache.NodeCache.diff.HITS.v, $host.oak.PersistentCache.NodeCache.diff.REQUESTS.v), 4)"
    },
    {
     "target": "aliasByNode(asPercent(#H, #G), 4, 5)",
     "targetFull": "aliasByNode(asPercent($host.oak.PersistentCache.NodeCache.local.diff.HITS.v, $host.oak.PersistentCache.NodeCache.local.diff.REQUESTS.v), 4, 5)"
    },
    {
     "target": "aliasByNode(asPercent(#K, #J), 4)",
     "targetFull": "aliasByNode(asPercent($host.oak.PersistentCache.NodeCache.node.HITS.v, $host.oak.PersistentCache.NodeCache.node.REQUESTS.v), 4)"
    },
    {
     "target": "aliasByNode(asPercent(#N, #M), 4, 5)",
     "targetFull": "aliasByNode(asPercent($host.oak.PersistentCache.NodeCache.prev.document.HITS.v, $host.oak.PersistentCache.NodeCache.prev.document.REQUESTS.v), 4, 5)"
    }
   ]
  },
  {
   "title": "PersistentCache - requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($host.oak.PersistentCache.NodeCache.*.REQUESTS.v, 4)"
    },
    {
     "target": "aliasByNode($host.oak.PersistentCache.NodeCache.*.*.REQUESTS.v, 4, 5)"
    }
   ]
  }
 ]
}